# Generated by Django 5.0.1 on 2024-08-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_buy_order_status_alter_buy_date_of_buying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.IntegerField(default=28000),
            preserve_default=False,
        ),
    ]
