# Generated by Django 5.0.1 on 2024-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_buy_delivery_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.EmailField(default=27, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='password',
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
    ]
