# Generated by Django 5.0.7 on 2024-08-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delivery_email_delivery_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='phonenumber',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
