# Generated by Django 5.0.7 on 2024-08-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delivery_name_delivery_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
    ]
