# Generated by Django 5.0.7 on 2024-08-28 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_delivery_product_remove_delivery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='delivery',
        ),
        migrations.CreateModel(
            name='delpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.TextField()),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buy')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.delivery')),
            ],
        ),
    ]
