# Generated by Django 5.0.7 on 2024-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_buy_delivery_delpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delpro',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
