# Generated by Django 5.0.7 on 2024-08-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_buy_del_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='del_boy',
            field=models.BooleanField(default=False),
        ),
    ]
